version: 0.2

phases:
  install:
    commands:
      # Move to the correct directory
      - cd server

      # Install dependencies needed for running tests
      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
