version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli

  build:
    commands:
      - npm run build-ts
      - mv -v src/server.ts .

artifacts:
  type: zip
  files:
    - server.ts
    - package.json
    - package-lock.json
    - dist/**/*
    - docs/**/*
    - node_modules/**/*
