path:
  /users/{userId}/settings:
    put:
      summary: Update the user's settings.
      tags: [Users]
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: Object ID of the user
      produces:
        application/json
      responses:
        "200":
          description: Returns the updated user document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          descrption: Count unsuccessful
          content:
            application/json:
              schema:
                type: string