path:
  /user/{userId}/settings:
    put:
      summary: Update the user's settings.
      tags: [Users]
      produces:
        application/json
      responses:
        "200":
          description: Returns the updated user document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          descrption: Count unsuccessful
          content:
            application/json:
              schema:
                type: string