import { EventEmitter } from 'events';
import { firstSessionSubscriber } from './first-session.subscriber';
import { fullyGreenHikeSubscriber } from './fully-green-hike.subscriber';
import { levelUpSubscriber } from './level-up.subscriber';
import { MessageTypes } from './message-types';
import { theWholeWeekLongSubscriber } from './the-whole-week-long.subscriber';
import { realHikerSubscriber } from './real-hiker.subscriber';
import { anEntireDaySubscriber } from './an-entire-day.subscriber';
import { threeADaySubscriber } from './three-a-day.subscriber';
import { quickPerSubscriber } from './quick-per.subscriber';
import { hoursAndHoursSubscriber } from './hours-and-hours.subscriber';
import { greenillionSubscriber } from './greenillion.subscriber';
import { aroundTheEquatorSubscriber } from './around-the-equator.subscriber';
import { poleToPoleSubscriber } from './pole-to-pole.subscriber';
import { lindesnesNordkappSubscriber } from './lindesnes-nordkapp.subscriber';
import { quickHikeSubscriber } from './quick-hike.subscriber';
import { aStrollSubscriber } from './a-stroll.subscriber';
import { aRealTripSubscriber } from './a-real-trip.subscriber';
import { chieftainSubscriber } from './chieftain.subscriber';
import { kingOfTheHillSubscriber } from './king-of-the-hill.subscriber';
import { localChampionSubscriber } from './local-champion.subscriber';

export const Broker = new EventEmitter(); 
Broker.setMaxListeners(20);

Broker.on(MessageTypes.newSession, theWholeWeekLongSubscriber);
Broker.on(MessageTypes.newSession, realHikerSubscriber);
Broker.on(MessageTypes.newSession, anEntireDaySubscriber);
Broker.on(MessageTypes.newSession, threeADaySubscriber);
Broker.on(MessageTypes.newSession, quickPerSubscriber);
Broker.on(MessageTypes.newSession, hoursAndHoursSubscriber);
Broker.on(MessageTypes.newSession, fullyGreenHikeSubscriber);
Broker.on(MessageTypes.newSession, firstSessionSubscriber);
Broker.on(MessageTypes.newSession, greenillionSubscriber);
Broker.on(MessageTypes.newSession, aroundTheEquatorSubscriber);
Broker.on(MessageTypes.newSession, poleToPoleSubscriber);
Broker.on(MessageTypes.newSession, lindesnesNordkappSubscriber);
Broker.on(MessageTypes.newSession, quickHikeSubscriber);
Broker.on(MessageTypes.newSession, aStrollSubscriber);
Broker.on(MessageTypes.newSession, aRealTripSubscriber);
Broker.on(MessageTypes.pointsAdded, chieftainSubscriber);
Broker.on(MessageTypes.pointsAdded, kingOfTheHillSubscriber);
Broker.on(MessageTypes.pointsAdded, localChampionSubscriber);
Broker.on(MessageTypes.pointsAdded, levelUpSubscriber);